name: Daily Ingest
on:
  schedule:
    - cron: '30 3 * * *'   # 09:00 IST = 03:30 UTC
  workflow_dispatch:
jobs:
  build-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run ingest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Commit & push
        run: |
          git config user.name "news-bot"
          git config user.email "bot@users.noreply.github.com"
          git add public/data/items.json data/cache || true
          git diff --quiet && echo "No changes" || git commit -m "chore: daily ingest"
      - uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
