name: Daily Ingest
on:
  schedule:
    - cron: '30 3 * * *'   # 09:00 IST = 03:30 UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
          
      - run: npm ci
      
      - name: Show current state
        run: |
          echo "=== BEFORE INGESTION ==="
          echo "Working directory: $(pwd)"
          echo "Files in public/data/:"
          ls -la public/data/ || echo "Directory doesn't exist"
          if [ -f "public/data/items.json" ]; then
            echo "Current file size: $(wc -c < public/data/items.json) bytes"
            echo "Current content preview:"
            head -200 public/data/items.json
          fi
          echo "=== GIT STATUS BEFORE ==="
          git status --porcelain
      
      - run: npm run ingest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Show what changed
        run: |
          echo "=== AFTER INGESTION ==="
          if [ -f "public/data/items.json" ]; then
            echo "New file size: $(wc -c < public/data/items.json) bytes"
            echo "New content preview:"
            head -200 public/data/items.json
          fi
          echo "=== GIT STATUS AFTER ==="
          git status --porcelain
          echo "=== GIT DIFF ==="
          git diff --name-only
          git diff public/data/items.json || echo "No diff for items.json"
          
      - name: Force add and commit
        run: |
          echo "=== FORCING GIT OPERATIONS ==="
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add timestamp to guarantee changes
          echo "Last updated: $(date)" >> public/data/timestamp.txt
          
          # Force add files
          git add -A
          
          echo "=== GIT STATUS AFTER ADD ==="
          git status --porcelain
          
          # Always try to commit
          if git commit -m "chore: daily ingest $(date +'%Y-%m-%d %H:%M')"; then
            echo "✅ Commit successful"
            git push
            echo "✅ Push successful"
          else
            echo "❌ Nothing to commit"
          fi
